# Gradle 守护进程内存与编码
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
# 并行构建与缓存
org.gradle.parallel=true
org.gradle.caching=true
# 配置缓存
org.gradle.configuration-cache=true
# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true
# Kotlin 代码风格
kotlin.code.style=official

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
